export const GET_LANDING_DATA = 'GET_LANDING_DATA';
export const SET_LOADING = 'SET_LOADING';

export const REGISTER_USER = 'REGISTER_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
