# Generated by Django 2.0.7 on 2018-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
