# Generated by Django 2.0.7 on 2018-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180724_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
